### PR TITLE
move legend outside of the chart

### PR DESCRIPTION
**Pull request by alexott**
the legend takes quite a lot of space on the chart itself, hiding the data.  This patch
moves the legend outside of the chart

### CODE REVIEW

**Comment by t2y** [comment]
I run iostat-tool with sample data after applied your patch.

```bash
(iostat) $ iostat-cli --data tests/fixtures/sample_iostat.output --disk sda --fig-output my-iostat.png plot
```

Legend of cpuplot is seems good, however I think legend of device plots on left side still covers device plots on right side. Could you resolve it?

my-iostat

**Comment by alexott** [comment]
Yes, I just pushed the fix for it...

**Comment by t2y** [comment]
LGTM. Thank you!

my-iostat

**Comment by alexott** [comment]
Thank you for fast response!

**Pull request merged**
